version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app
    links:
      - db
  
  db:
    container_name: db
    image: library/mysql:5.6.22
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password



 