
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: development
  username: user
  password: password
  host: db

development:
  <<: *default

test:
  <<: *default
  database: projectmysql_test

production:
  <<: *default

